// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Fuck(arg1:string):Promise<string>;

export function GetVideoDetail():Promise<main.Videos>;

export function GetVideoList():Promise<Array<main.Videos>>;

export function Greet(arg1:string):Promise<string>;
